/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'pending' : IDL.Null,
  'fulfilled' : IDL.Null,
  'ready' : IDL.Null,
});
export const VehicleInfo = IDL.Record({
  'model' : IDL.Text,
  'licensePlate' : IDL.Text,
  'make' : IDL.Text,
  'color' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'vehicleInfo' : VehicleInfo,
  'customerMobile' : IDL.Text,
  'timestamp' : Timestamp,
  'items' : IDL.Vec(OrderItem),
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'orderId' : IDL.Nat,
  'acknowledged' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const OrderInput = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'vehicleInfo' : VehicleInfo,
  'customerMobile' : IDL.Text,
  'timestamp' : Timestamp,
  'items' : IDL.Vec(OrderItem),
});

export const idlService = IDL.Service({
  'acknowledgeAllNotifications' : IDL.Func([], [], []),
  'acknowledgeNotification' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getPendingOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUnacknowledgedCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnacknowledgedNotifications' : IDL.Func(
      [],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'placeOrder' : IDL.Func([OrderInput], [IDL.Nat], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'pending' : IDL.Null,
    'fulfilled' : IDL.Null,
    'ready' : IDL.Null,
  });
  const VehicleInfo = IDL.Record({
    'model' : IDL.Text,
    'licensePlate' : IDL.Text,
    'make' : IDL.Text,
    'color' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'vehicleInfo' : VehicleInfo,
    'customerMobile' : IDL.Text,
    'timestamp' : Timestamp,
    'items' : IDL.Vec(OrderItem),
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'orderId' : IDL.Nat,
    'acknowledged' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const OrderInput = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'vehicleInfo' : VehicleInfo,
    'customerMobile' : IDL.Text,
    'timestamp' : Timestamp,
    'items' : IDL.Vec(OrderItem),
  });
  
  return IDL.Service({
    'acknowledgeAllNotifications' : IDL.Func([], [], []),
    'acknowledgeNotification' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getPendingOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUnacknowledgedCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnacknowledgedNotifications' : IDL.Func(
        [],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'placeOrder' : IDL.Func([OrderInput], [IDL.Nat], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };